// Generiert von scripts/sync-profiles.ts — nicht von Hand bearbeiten.
import type { BrfParameter } from './brf-parser';

export const BROUTER_PROFILE_PARAMETERS: Readonly<Record<string, readonly BrfParameter[]>> = {
  fastbike: [
    {
      name: 'allow_ferries',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set to false to disallow ferries',
      documented: true,
    },
    {
      name: 'allow_motorways',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to allow motorways (useful in Asia / Oceania for example)',
      documented: true,
    },
    {
      name: 'allow_steps',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set to false to disallow steps',
      documented: true,
    },
    {
      name: 'bikerPower',
      type: 'number',
      defaultValue: '100',
      description: 'Average power (in W) provided by the biker, for travel time computation',
      documented: true,
    },
    {
      name: 'C_r',
      type: 'number',
      defaultValue: '0.01',
      description: 'Rolling resistance coefficient (dimensionless), for travel time computation',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set to false to ignore elevation in routing',
      documented: true,
    },
    {
      name: 'consider_forest',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route in forest or parks',
      documented: true,
    },
    {
      name: 'consider_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a low-noise route',
      documented: true,
    },
    {
      name: 'consider_river',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route along rivers, lakes, etc.',
      documented: true,
    },
    {
      name: 'consider_town',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to bypass cities / big towns as far as possible',
      documented: true,
    },
    {
      name: 'consider_traffic',
      type: 'number',
      defaultValue: '0.1',
      description:
        '%consider_traffic% | avoiding roads that usually have traffic is? | [1=very important, 0.5=pretty important, 0.3=important, 0.1=slightly preferred, 0.0=do not consider traffic]',
      documented: false,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set to true to take turn restrictions into account',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPoints',
      type: 'boolean',
      defaultValue: 'false',
      description:
        'Set to true to remove detours due to via points (going back and forth on the same route)',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPointsDistance',
      type: 'number',
      defaultValue: '400',
      description:
        'Only remove detours shorter than this (one-way) distance (in m) (engine defaults to 0 which removes detours whatever their length)',
      documented: true,
    },
    {
      name: 'downhillcost',
      type: 'number',
      defaultValue: '60',
      description: 'Cost for going downhill',
      documented: true,
    },
    {
      name: 'downhillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: 'Gradients below this value in percents are not counted.',
      documented: true,
    },
    {
      name: 'maxSpeed',
      type: 'number',
      defaultValue: '45',
      description: 'Absolute maximum speed (in km/h), for travel time computation',
      documented: true,
    },
    {
      name: 'processUnusedTags',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to output unused tags in data tab',
      documented: true,
    },
    {
      name: 'S_C_x',
      type: 'number',
      defaultValue: '0.225',
      description:
        'Drag coefficient times the reference area (in m^2), for travel time computation',
      documented: true,
    },
    {
      name: 'totalMass',
      type: 'number',
      defaultValue: '90',
      description: 'Mass (in kg) of the bike + biker, for travel time computation',
      documented: true,
    },
    {
      name: 'turnInstructionCatchingRange',
      type: 'number',
      defaultValue: '40',
      description:
        'Within this distance (in m) several turning instructions are combined into one and the turning angles are better approximated to the general direction',
      documented: true,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]',
      documented: false,
    },
    {
      name: 'turnInstructionRoundabouts',
      type: 'boolean',
      defaultValue: 'true',
      description:
        'Set to "false" to avoid generating special turning instructions for roundabouts',
      documented: true,
    },
    {
      name: 'uphillcost',
      type: 'number',
      defaultValue: '0',
      description: 'Cost for going uphill',
      documented: true,
    },
    {
      name: 'uphillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: 'Gradients below this value in percents are not counted.',
      documented: true,
    },
    {
      name: 'use_proposed_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to consider proposed and regular cycleroutes as equals',
      documented: true,
    },
    {
      name: 'validForBikes',
      type: 'boolean',
      defaultValue: 'true',
      description: '',
      documented: false,
    },
  ],
  'fastbike-lowtraffic': [
    {
      name: 'allow_ferries',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set to false to disallow ferries',
      documented: true,
    },
    {
      name: 'allow_motorways',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to allow motorways (useful in Asia / Oceania for example)',
      documented: true,
    },
    {
      name: 'allow_steps',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set to false to disallow steps',
      documented: true,
    },
    {
      name: 'bikerPower',
      type: 'number',
      defaultValue: '100',
      description: 'Average power (in W) provided by the biker, for travel time computation',
      documented: true,
    },
    {
      name: 'C_r',
      type: 'number',
      defaultValue: '0.01',
      description: 'Rolling resistance coefficient (dimensionless), for travel time computation',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set to false to ignore elevation in routing',
      documented: true,
    },
    {
      name: 'consider_forest',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route in forest or parks',
      documented: true,
    },
    {
      name: 'consider_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a low-noise route',
      documented: true,
    },
    {
      name: 'consider_river',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route along rivers, lakes, etc.',
      documented: true,
    },
    {
      name: 'consider_town',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to bypass cities / big towns as far as possible',
      documented: true,
    },
    {
      name: 'consider_traffic',
      type: 'boolean',
      defaultValue: 'true',
      description:
        '%consider_traffic% | avoiding roads that usually have traffic is? | [1=very important, 0.5=pretty important, 0.3=important, 0.1=slightly preferred, 0.0=do not consider traffic]',
      documented: false,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set to true to take turn restrictions into account',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPoints',
      type: 'boolean',
      defaultValue: 'false',
      description:
        'Set to true to remove detours due to via points (going back and forth on the same route)',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPointsDistance',
      type: 'number',
      defaultValue: '400',
      description:
        'Only remove detours shorter than this (one-way) distance (in m) (engine defaults to 0 which removes detours whatever their length)',
      documented: true,
    },
    {
      name: 'downhillcost',
      type: 'number',
      defaultValue: '60',
      description: 'Cost for going downhill',
      documented: true,
    },
    {
      name: 'downhillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: 'Gradients below this value in percents are not counted.',
      documented: true,
    },
    {
      name: 'maxSpeed',
      type: 'number',
      defaultValue: '45',
      description: 'Absolute maximum speed (in km/h), for travel time computation',
      documented: true,
    },
    {
      name: 'processUnusedTags',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to output unused tags in data tab',
      documented: true,
    },
    {
      name: 'S_C_x',
      type: 'number',
      defaultValue: '0.225',
      description:
        'Drag coefficient times the reference area (in m^2), for travel time computation',
      documented: true,
    },
    {
      name: 'totalMass',
      type: 'number',
      defaultValue: '90',
      description: 'Mass (in kg) of the bike + biker, for travel time computation',
      documented: true,
    },
    {
      name: 'turnInstructionCatchingRange',
      type: 'number',
      defaultValue: '40',
      description:
        'Within this distance (in m) several turning instructions are combined into one and the turning angles are better approximated to the general direction',
      documented: true,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]',
      documented: false,
    },
    {
      name: 'turnInstructionRoundabouts',
      type: 'boolean',
      defaultValue: 'true',
      description:
        'Set to "false" to avoid generating special turning instructions for roundabouts',
      documented: true,
    },
    {
      name: 'uphillcost',
      type: 'number',
      defaultValue: '0',
      description: 'Cost for going uphill',
      documented: true,
    },
    {
      name: 'uphillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: 'Gradients below this value in percents are not counted.',
      documented: true,
    },
    {
      name: 'use_proposed_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to consider proposed and regular cycleroutes as equals',
      documented: true,
    },
    {
      name: 'validForBikes',
      type: 'boolean',
      defaultValue: 'true',
      description: '',
      documented: false,
    },
  ],
  'fastbike-verylowtraffic': [
    {
      name: 'avoid_path',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to avoid pathes',
      documented: true,
    },
    {
      name: 'consider_crossing',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set to true to add penalty by unprotected intersections',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set true to favor a route with few elevation meters',
      documented: true,
    },
    {
      name: 'consider_forest',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a route in forest or parks',
      documented: true,
    },
    {
      name: 'consider_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a low-noise route',
      documented: true,
    },
    {
      name: 'consider_river',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a route along rivers or sees',
      documented: true,
    },
    {
      name: 'consider_town',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to bypass cities / big towns as far as possible',
      documented: true,
    },
    {
      name: 'consider_traffic',
      type: 'number',
      defaultValue: '1',
      description:
        '%consider_traffic% | how do you plan to drive the tour? |  [1=as cyclist alone in the week, 0.5=as cyclist alone at weekend, 0.3 =with a group of cyclists, 0.1=with a group of cyclists at week-end, 0.0=do not consider traffic]',
      documented: false,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: 'turn restrictions are considered',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class1',
      type: 'number',
      defaultValue: '82',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class2',
      type: 'number',
      defaultValue: '112',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class3',
      type: 'number',
      defaultValue: '212',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class4',
      type: 'number',
      defaultValue: '312',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class5',
      type: 'number',
      defaultValue: '512',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class6',
      type: 'number',
      defaultValue: '712',
      description: '',
      documented: false,
    },
    {
      name: 'crossing_Prio_H',
      type: 'number',
      defaultValue: '22',
      description: 'min priorityclassifier to consider the HW as "Highprio" HW',
      documented: false,
    },
    {
      name: 'crossing_Prio_L',
      type: 'number',
      defaultValue: '21',
      description: 'max priorityclassifier to consider the HW as "Lowprio" HW',
      documented: false,
    },
    {
      name: 'cycleway_lane_penalty',
      type: 'number',
      defaultValue: '0',
      description:
        '0 => when lane, no cost for traffic or max speed, 1 => same cost as on the highway itself: example 0.3',
      documented: false,
    },
    {
      name: 'processUnusedTags',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true if you want to display all tags in the "data"',
      documented: false,
    },
    {
      name: 'turnInstructionCatchingRange',
      type: 'number',
      defaultValue: '6',
      description: '2 turn instructions are generated only when distance > 8 m',
      documented: false,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]',
      documented: false,
    },
    {
      name: 'turnInstructionRoundabouts',
      type: 'boolean',
      defaultValue: 'true',
      description: 'roundabout, no "take exit N" (as "N" may be confusing compared to car)',
      documented: false,
    },
    {
      name: 'validForBikes',
      type: 'number',
      defaultValue: '1',
      description: '',
      documented: false,
    },
  ],
  gravel: [
    {
      name: 'add_beeline',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable beeline on distant start/end points',
      documented: true,
    },
    {
      name: 'assume_wet_conditions',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to assume wet conditions',
      documented: true,
    },
    {
      name: 'avoid_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to avoid noisy areas',
      documented: true,
    },
    {
      name: 'avoid_steep_inclines',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to avoid steep inclines',
      documented: true,
    },
    {
      name: 'avoid_towns',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to avoid urban areas',
      documented: true,
    },
    {
      name: 'bikerPower',
      type: 'number',
      defaultValue: '150',
      description: 'Average power (W) provided by the biker',
      documented: true,
    },
    {
      name: 'C_r',
      type: 'number',
      defaultValue: '0.005',
      description: 'Rolling resistance coefficient (dimensionless)',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to consider elevation',
      documented: true,
    },
    {
      name: 'consider_traffic_estimate',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to consider traffic estimates',
      documented: true,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: '',
      documented: false,
    },
    {
      name: 'correctMisplacedViaPoints',
      type: 'boolean',
      defaultValue: 'false',
      description:
        'Set to true to remove detours due to via points (going back and forth on the same route)',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPointsDistance',
      type: 'number',
      defaultValue: '400',
      description:
        'Only remove detours shorter than this (one-way) distance (in m) (engine defaults to 0 which removes detours whatever their length)',
      documented: true,
    },
    {
      name: 'maxSpeed',
      type: 'number',
      defaultValue: '35',
      description: 'Absolute maximum speed (km/h)',
      documented: true,
    },
    {
      name: 'pass1coefficient',
      type: 'number',
      defaultValue: '4',
      description: '',
      documented: false,
    },
    {
      name: 'prefer_cycle_routes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to prefer cycle routes',
      documented: true,
    },
    {
      name: 'prefer_forests',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to prefer forest areas',
      documented: true,
    },
    {
      name: 'prefer_rivers',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to prefer river valleys',
      documented: true,
    },
    {
      name: 'prefer_unpaved_paths',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable to prefer unpaved paths',
      documented: true,
    },
    {
      name: 'S_C_x',
      type: 'number',
      defaultValue: '0.300',
      description: 'Drag coefficient times reference area (m^2) times half air density (kg/m^3)',
      documented: true,
    },
    {
      name: 'totalMass',
      type: 'number',
      defaultValue: '90',
      description: 'Mass (kg) of the bike + biker',
      documented: true,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn-by-turn directions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=oruxmaps-style]',
      documented: false,
    },
    {
      name: 'turnInstructionRoundabouts',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Special turn-by-turn directions for roundabouts',
      documented: true,
    },
    {
      name: 'use_proposed_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to consider proposed and regular cycleroutes as equals',
      documented: true,
    },
    {
      name: 'validForBikes',
      type: 'boolean',
      defaultValue: 'true',
      description: '',
      documented: false,
    },
  ],
  'hiking-beta': [
    {
      name: 'allow_ferries',
      type: 'number',
      defaultValue: '1',
      description: '1 as default',
      documented: false,
    },
    {
      name: 'allow_steps',
      type: 'number',
      defaultValue: '1',
      description: '1 as default',
      documented: false,
    },
    {
      name: 'consider_elevation',
      type: 'number',
      defaultValue: '1',
      description: '0 as default, otherwise less interesting flat roads are chosen.',
      documented: false,
    },
    {
      name: 'cost_of_unknown',
      type: 'number',
      defaultValue: '2',
      description: '2 as default',
      documented: false,
    },
    {
      name: 'downhillcostvalue',
      type: 'number',
      defaultValue: '7',
      description: '',
      documented: false,
    },
    {
      name: 'downhillcutoffvalue',
      type: 'number',
      defaultValue: '3',
      description: '',
      documented: false,
    },
    {
      name: 'elevationbufferreduce',
      type: 'number',
      defaultValue: '0.0',
      description: '0.0 as default',
      documented: false,
    },
    {
      name: 'elevationmaxbuffer',
      type: 'number',
      defaultValue: '10',
      description: '10 as default',
      documented: false,
    },
    {
      name: 'elevationpenaltybuffer',
      type: 'number',
      defaultValue: '5',
      description: '5 as default',
      documented: false,
    },
    {
      name: 'initialcost_value',
      type: 'number',
      defaultValue: '0',
      description: '50 as default, not used now',
      documented: false,
    },
    {
      name: 'iswet',
      type: 'number',
      defaultValue: '0',
      description: '0 as default, 1 tries to prevent muddy boots and wet buttocks',
      documented: false,
    },
    {
      name: 'non_hiking_route_penalty',
      type: 'number',
      defaultValue: '0.15',
      description: '0.25 as default, used with prefer_hiking_routes',
      documented: false,
    },
    {
      name: 'non_sticky_route_penalty',
      type: 'number',
      defaultValue: '0.5',
      description: '1.0 as default, used stick_to_hiking_routes  #v1.5',
      documented: false,
    },
    {
      name: 'prefer_hiking_routes',
      type: 'number',
      defaultValue: '1',
      description:
        '1 as default, gives penalty to way not being hiking route and cancels route turncost',
      documented: false,
    },
    {
      name: 'SAC_access_penalty',
      type: 'number',
      defaultValue: '9000',
      description: 'costfactor 9999 means the most horrible but allowed road.,',
      documented: false,
    },
    {
      name: 'SAC_K1',
      type: 'number',
      defaultValue: '0.1',
      description: 'Penalizing of SAC levels below preferred',
      documented: false,
    },
    {
      name: 'SAC_K2',
      type: 'number',
      defaultValue: '0.6',
      description: 'Penalizing of SAC levels above preferred',
      documented: false,
    },
    {
      name: 'SAC_scale_limit',
      type: 'number',
      defaultValue: '3',
      description: '0..6, 0 to avoid any SAC paths, 1 for T1 as maximum, 6 for T6 as maximum',
      documented: false,
    },
    {
      name: 'SAC_scale_preferred',
      type: 'number',
      defaultValue: '1',
      description:
        'The same, but the preferred SAC scale level. Level below are slightly, above strongly penalized',
      documented: false,
    },
    {
      name: 'shortest_way',
      type: 'number',
      defaultValue: '0',
      description: '0 as default',
      documented: false,
    },
    {
      name: 'stick_to_hiking_routes',
      type: 'number',
      defaultValue: '0',
      description:
        '0 as default, as above, but gives higher penalty costfactor + way/node initial costs',
      documented: false,
    },
    {
      name: 'turncost_value',
      type: 'number',
      defaultValue: '0',
      description: '20 as default, not used now',
      documented: false,
    },
    {
      name: 'uphillcostvalue',
      type: 'number',
      defaultValue: '7',
      description: '',
      documented: false,
    },
    {
      name: 'uphillcutoffvalue',
      type: 'number',
      defaultValue: '3',
      description: '',
      documented: false,
    },
    { name: 'validForFoot', type: 'number', defaultValue: '1', description: '', documented: false },
  ],
  'hiking-mountain': [
    {
      name: 'add_beeline',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable beeline on distant start/end points',
      documented: true,
    },
    {
      name: 'allow_ferries',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set to false to disallow ferries',
      documented: true,
    },
    {
      name: 'allow_steps',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set to false to disallow steps',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route with few elevation meters',
      documented: true,
    },
    {
      name: 'consider_forest',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route in forest or green areas',
      documented: true,
    },
    {
      name: 'consider_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a low-noise route',
      documented: true,
    },
    {
      name: 'consider_river',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route along rivers, lakes, etc.',
      documented: true,
    },
    {
      name: 'consider_town',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to bypass cities / big towns as far as possible',
      documented: true,
    },
    {
      name: 'cost_of_unknown',
      type: 'number',
      defaultValue: '2',
      description: '2 as default',
      documented: false,
    },
    {
      name: 'downhillcostvalue',
      type: 'number',
      defaultValue: '7',
      description: '',
      documented: false,
    },
    {
      name: 'downhillcutoffvalue',
      type: 'number',
      defaultValue: '3',
      description: '',
      documented: false,
    },
    {
      name: 'elevationbufferreduce',
      type: 'number',
      defaultValue: '1.0',
      description: '0.0 as default',
      documented: false,
    },
    {
      name: 'elevationmaxbuffer',
      type: 'number',
      defaultValue: '10',
      description: '10 as default',
      documented: false,
    },
    {
      name: 'elevationpenaltybuffer',
      type: 'number',
      defaultValue: '5',
      description: '5 as default',
      documented: false,
    },
    {
      name: 'hiking_routes_preference',
      type: 'number',
      defaultValue: '0.20',
      description:
        'Increases cost of non hiking routes by multiplier 1 + hiking_routes_preference (0.10 to 2.0)',
      documented: true,
    },
    {
      name: 'initialcost_value',
      type: 'number',
      defaultValue: '0',
      description: 'not used now',
      documented: false,
    },
    {
      name: 'iswet',
      type: 'boolean',
      defaultValue: '0',
      description: 'tries to prevent muddy boots and wet buttocks',
      documented: true,
    },
    {
      name: 'Offroad_factor',
      type: 'number',
      defaultValue: '0.0',
      description:
        'default 0.0, see ****), see also https://github.com/poutnikl/Brouter-profiles/wiki/Trekking-MTB-Profiles---legend',
      documented: false,
    },
    {
      name: 'path_preference',
      type: 'number',
      defaultValue: '0.0',
      description: '0.0 as default, try 20.0 to penalize nonpath ways a/o paved ways',
      documented: false,
    },
    {
      name: 'SAC_access_penalty',
      type: 'number',
      defaultValue: '9000',
      description: 'costfactor 9999 means the most horrible but allowed road.,',
      documented: false,
    },
    {
      name: 'SAC_K1',
      type: 'number',
      defaultValue: '0.05',
      description: 'Penalizing of SAC levels below preferred',
      documented: false,
    },
    {
      name: 'SAC_K2',
      type: 'number',
      defaultValue: '0.6',
      description: 'Penalizing of SAC levels above preferred',
      documented: false,
    },
    {
      name: 'SAC_scale_limit',
      type: 'number',
      defaultValue: '3',
      description:
        '%SAC_scale_limit% | all paths with sac_scale higher than  SAC_scale_limit are forbidden | [0=avoid any SAC paths, 1=SAC T1, 2=SAC T2, 3=SAC T3, 4=SAC T4, 5=SAC T5, 6=SAC T6]',
      documented: false,
    },
    {
      name: 'SAC_scale_preferred',
      type: 'number',
      defaultValue: '1',
      description:
        '%SAC_scale_preferred% | The same, but the preferred SAC scale level. Level below are slightly, above strongly penalized | [0=avoid any SAC paths, 1=SAC T1, 2=SAC T2, 3=SAC T3, 4=SAC T4, 5=SAC T5, 6=SAC T6]',
      documented: false,
    },
    {
      name: 'shortest_way',
      type: 'number',
      defaultValue: '0',
      description:
        '0 as default, duplicate shortest standard profile, SAC access limit ignored for now',
      documented: false,
    },
    {
      name: 'turncost_value',
      type: 'number',
      defaultValue: '0',
      description: 'not used now',
      documented: false,
    },
    {
      name: 'turnInstructionCatchingRange',
      type: 'number',
      defaultValue: '20',
      description:
        'V1.8.5 / default=40, but foot paths may be more distinguished, especially in cities.',
      documented: false,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]',
      documented: false,
    },
    {
      name: 'uphillcostvalue',
      type: 'number',
      defaultValue: '7',
      description: '',
      documented: false,
    },
    {
      name: 'uphillcutoffvalue',
      type: 'number',
      defaultValue: '3',
      description: '',
      documented: false,
    },
    {
      name: 'use_proposed_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to consider proposed and regular cycleroutes as equals',
      documented: true,
    },
    { name: 'validForFoot', type: 'number', defaultValue: '1', description: '', documented: false },
  ],
  mtb: [
    {
      name: 'add_beeline',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable beeline on distant start/end points',
      documented: true,
    },
    {
      name: 'allow_default_barrier_restriction',
      type: 'boolean',
      defaultValue: 'false',
      description: 'If true, default access for barrier=gate is false. see node context',
      documented: false,
    },
    {
      name: 'allow_ferries',
      type: 'number',
      defaultValue: '1',
      description: '1 as default',
      documented: false,
    },
    {
      name: 'allow_steps',
      type: 'number',
      defaultValue: '0',
      description: '1 as default',
      documented: false,
    },
    {
      name: 'allow_traffic_penalty',
      type: 'number',
      defaultValue: '1',
      description: '1 as default',
      documented: false,
    },
    {
      name: 'avoid_unsafe',
      type: 'number',
      defaultValue: '0',
      description: '0 as default, gives penalty to mainroad without bike friendly status.',
      documented: false,
    },
    {
      name: 'c_ford_costfactor',
      type: 'number',
      defaultValue: '50',
      description: '',
      documented: false,
    },
    {
      name: 'c_ford_initialcost_node',
      type: 'number',
      defaultValue: '500',
      description: '',
      documented: false,
    },
    {
      name: 'c_ford_initialcost_way',
      type: 'number',
      defaultValue: '1000',
      description: '',
      documented: false,
    },
    {
      name: 'consider_elevation',
      type: 'number',
      defaultValue: '1',
      description: '1 as default',
      documented: false,
    },
    {
      name: 'consider_smoothness',
      type: 'number',
      defaultValue: '1',
      description: '1 as default',
      documented: false,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: 'v2.5.11',
      documented: false,
    },
    {
      name: 'correctMisplacedViaPoints',
      type: 'boolean',
      defaultValue: 'false',
      description:
        'Set to true to remove detours due to via points (going back and forth on the same route)',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPointsDistance',
      type: 'number',
      defaultValue: '400',
      description:
        'Only remove detours shorter than this (one-way) distance (in m) (engine defaults to 0 which removes detours whatever their length)',
      documented: true,
    },
    {
      name: 'cost_of_unknown',
      type: 'number',
      defaultValue: '2.0',
      description: '2 as default, cost of highway=',
      documented: false,
    },
    {
      name: 'cycleroutes_pref',
      type: 'number',
      defaultValue: '0.2',
      description: 'also CRP *)  costfactor penalty for not being cycleroute',
      documented: false,
    },
    {
      name: 'downhillCFshift',
      type: 'number',
      defaultValue: '0.0',
      description: 'prioritizing/penalizing of up/downhills, based on length, not elevation',
      documented: false,
    },
    {
      name: 'hills',
      type: 'number',
      defaultValue: '0',
      description:
        '1=default / 0=BRouter default/ 1=+ penalty for uphills >3.0%/ 2=velomobile-like avoiding slopes, 3= simulates ascend/length time equiv.',
      documented: false,
    },
    {
      name: 'isbike_for_mainroads',
      type: 'boolean',
      defaultValue: 'true',
      description:
        'default=true / if false then bike friendly tag hints for mainroads are ignored, keeping their high penalties. v2.5.20',
      documented: false,
    },
    {
      name: 'iswet',
      type: 'number',
      defaultValue: '0',
      description: '0 as default, *) flag for weather conditions',
      documented: false,
    },
    {
      name: 'million',
      type: 'number',
      defaultValue: '1000000',
      description: '',
      documented: false,
    },
    {
      name: 'MTB_factor',
      type: 'number',
      defaultValue: '0.0',
      description: 'default 0.0, *)',
      documented: false,
    },
    {
      name: 'originalisbike',
      type: 'boolean',
      defaultValue: 'false',
      description: '',
      documented: false,
    },
    {
      name: 'pass1coefficient',
      type: 'number',
      defaultValue: '1.8',
      description: '',
      documented: false,
    },
    {
      name: 'pass2coefficient',
      type: 'number',
      defaultValue: '0',
      description: '',
      documented: false,
    },
    {
      name: 'path_preference',
      type: 'number',
      defaultValue: '20.0',
      description:
        '20.0 as default, the bigger it is the bigger it penalizes nonpath ways a/o paved ways',
      documented: false,
    },
    {
      name: 'processUnusedTags',
      type: 'number',
      defaultValue: '0',
      description:
        '1 is old Brouter behaviour, 0 is new Brouter default, more efficient, but ignores tags not used by a profile.',
      documented: false,
    },
    {
      name: 'smallpaved_factor',
      type: 'number',
      defaultValue: '-0.5',
      description: 'default 0.0, *)',
      documented: false,
    },
    {
      name: 'StrictNOBicycleaccess',
      type: 'number',
      defaultValue: '0',
      description: '0 allows but penalizes foot only access / 1 forbides foot only access.',
      documented: false,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description: '0=none, 1=auto-choose, 2=locus-style, 3=osmand-style',
      documented: false,
    },
    { name: 'UDcostON', type: 'boolean', defaultValue: 'true', description: '', documented: false },
    {
      name: 'unsafe_penalty_value',
      type: 'number',
      defaultValue: '1.0',
      description: '1 - was 2 in Trekking, but this may cause U-like safe routes',
      documented: false,
    },
    {
      name: 'uphillCFshift',
      type: 'number',
      defaultValue: '0.0',
      description: 'experimental shifting of up/downhillcostfactors as alternative way of',
      documented: false,
    },
    {
      name: 'use_proposed_cn',
      type: 'number',
      defaultValue: '1',
      description:
        '0 as default, considers proposed cycle networks as unmarked but valid cycleroutes.',
      documented: false,
    },
    {
      name: 'use_proposed_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to consider proposed and regular cycleroutes as equals',
      documented: true,
    },
    {
      name: 'validForBikes',
      type: 'number',
      defaultValue: '1',
      description: '',
      documented: false,
    },
    {
      name: 'valley_nonflat_multiplier',
      type: 'number',
      defaultValue: '2.0',
      description: '',
      documented: false,
    },
  ],
  MTB_SB_light: [
    {
      name: 'avoid_path',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to avoid pathes',
      documented: true,
    },
    {
      name: 'consider_crossing',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set to true to add penalty by crossing',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set true to favor a route with few elevation meters',
      documented: true,
    },
    {
      name: 'consider_forest',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a route in forest or parks',
      documented: true,
    },
    {
      name: 'consider_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a low-noise route',
      documented: true,
    },
    {
      name: 'consider_river',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a route along rivers or sees',
      documented: true,
    },
    {
      name: 'consider_town',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to bypass cities / big towns as far as possible',
      documented: true,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: 'turn restrictions are considered',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class1',
      type: 'number',
      defaultValue: '82',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class2',
      type: 'number',
      defaultValue: '112',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class3',
      type: 'number',
      defaultValue: '212',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class4',
      type: 'number',
      defaultValue: '312',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class5',
      type: 'number',
      defaultValue: '412',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class6',
      type: 'number',
      defaultValue: '712',
      description: '',
      documented: false,
    },
    {
      name: 'crossing_Prio_H',
      type: 'number',
      defaultValue: '22',
      description: 'min priorityclassifier to consider the HW as "Highprio" HW',
      documented: false,
    },
    {
      name: 'crossing_Prio_L',
      type: 'number',
      defaultValue: '21',
      description: 'max priorityclassifier to consider the HW as "Lowprio" HW',
      documented: false,
    },
    {
      name: 'cycleway_lane_penalty',
      type: 'number',
      defaultValue: '0',
      description: '0 => no cost, 1 => same cost as highway itself: example 0.3',
      documented: true,
    },
    {
      name: 'downhillcost',
      type: 'number',
      defaultValue: '60',
      description: '',
      documented: false,
    },
    {
      name: 'processUnusedTags',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true if you want to display all tags in the "data"',
      documented: false,
    },
    {
      name: 'turnInstructionCatchingRange',
      type: 'number',
      defaultValue: '2',
      description: '2 turn instructions are generated only when distance > 8 m',
      documented: false,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style]',
      documented: false,
    },
    {
      name: 'turnInstructionRoundabouts',
      type: 'boolean',
      defaultValue: 'false',
      description: 'roundabout, no "take exit N" (as "N" may be confusing compared to car)',
      documented: false,
    },
    { name: 'uphillcost', type: 'number', defaultValue: '100', description: '', documented: false },
    {
      name: 'validForBikes',
      type: 'number',
      defaultValue: '1',
      description: '',
      documented: false,
    },
  ],
  'racebike-verylowtraffic': [
    {
      name: 'avoid_path',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to avoid pathes',
      documented: true,
    },
    {
      name: 'consider_crossing',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set to true to add penalty by unprotected intersections',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'true',
      description: 'set true to favor a route with few elevation meters',
      documented: true,
    },
    {
      name: 'consider_forest',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a route in forest or parks',
      documented: true,
    },
    {
      name: 'consider_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a low-noise route',
      documented: true,
    },
    {
      name: 'consider_river',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to favor a route along rivers or sees',
      documented: true,
    },
    {
      name: 'consider_town',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true to bypass cities / big towns as far as possible',
      documented: true,
    },
    {
      name: 'consider_traffic',
      type: 'number',
      defaultValue: '1',
      description:
        '%consider_traffic% | how do you plan to drive the tour? |  [1=as cyclist alone in the week, 0.5=as cyclist alone at weekend, 0.3 =with a group of cyclists, 0.1=with a group of cyclists at week-end, 0.0=do not consider traffic]',
      documented: false,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: 'turn restrictions are considered',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class1',
      type: 'number',
      defaultValue: '82',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class2',
      type: 'number',
      defaultValue: '112',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class3',
      type: 'number',
      defaultValue: '212',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class4',
      type: 'number',
      defaultValue: '312',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class5',
      type: 'number',
      defaultValue: '512',
      description: '',
      documented: false,
    },
    {
      name: 'cost_ToLeft_from_H_class6',
      type: 'number',
      defaultValue: '712',
      description: '',
      documented: false,
    },
    {
      name: 'crossing_Prio_H',
      type: 'number',
      defaultValue: '22',
      description: 'min priorityclassifier to consider the HW as "Highprio" HW',
      documented: false,
    },
    {
      name: 'crossing_Prio_L',
      type: 'number',
      defaultValue: '21',
      description: 'max priorityclassifier to consider the HW as "Lowprio" HW',
      documented: false,
    },
    {
      name: 'cycleway_lane_penalty',
      type: 'number',
      defaultValue: '0',
      description:
        '0 => when lane, no cost for traffic or max speed, 1 => same cost as on the highway itself: example 0.3',
      documented: false,
    },
    {
      name: 'processUnusedTags',
      type: 'boolean',
      defaultValue: 'false',
      description: 'set to true if you want to display all tags in the "data"',
      documented: false,
    },
    {
      name: 'turnInstructionCatchingRange',
      type: 'number',
      defaultValue: '6',
      description: '2 turn instructions are generated only when distance > 8 m',
      documented: false,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]',
      documented: false,
    },
    {
      name: 'turnInstructionRoundabouts',
      type: 'boolean',
      defaultValue: 'true',
      description: 'roundabout, no "take exit N" (as "N" may be confusing compared to car)',
      documented: false,
    },
    {
      name: 'validForBikes',
      type: 'number',
      defaultValue: '1',
      description: '',
      documented: false,
    },
  ],
  shortest: [
    { name: 'downhillcost', type: 'number', defaultValue: '0', description: '', documented: false },
    {
      name: 'downhillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: '',
      documented: false,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]',
      documented: false,
    },
    { name: 'uphillcost', type: 'number', defaultValue: '0', description: '', documented: false },
    {
      name: 'uphillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: '',
      documented: false,
    },
    {
      name: 'use_proposed_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to consider proposed and regular cycleroutes as equals',
      documented: true,
    },
    { name: 'validForFoot', type: 'number', defaultValue: '1', description: '', documented: false },
  ],
  trekking: [
    {
      name: 'add_beeline',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Enable beeline on distant start/end points',
      documented: true,
    },
    {
      name: 'allow_ferries',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set false to disallow ferries',
      documented: true,
    },
    {
      name: 'allow_steps',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set false to disallow steps',
      documented: true,
    },
    {
      name: 'avoid_unsafe',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set true to avoid standard highways',
      documented: true,
    },
    {
      name: 'bikerPower',
      type: 'number',
      defaultValue: '100',
      description: 'Average power (in W) provided by the biker, for travel time computation',
      documented: true,
    },
    {
      name: 'C_r',
      type: 'number',
      defaultValue: '0.01',
      description: 'Rolling resistance coefficient (dimensionless), for travel time computation',
      documented: true,
    },
    {
      name: 'consider_elevation',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set true to favor a route with few elevation meters',
      documented: true,
    },
    {
      name: 'consider_forest',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route in forest or parks',
      documented: true,
    },
    {
      name: 'consider_noise',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a low-noise route',
      documented: true,
    },
    {
      name: 'consider_river',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to prefer a route along rivers, lakes, etc.',
      documented: true,
    },
    {
      name: 'consider_town',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to bypass cities / big towns as far as possible',
      documented: true,
    },
    {
      name: 'consider_traffic',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Activate to consider traffic estimates',
      documented: true,
    },
    {
      name: 'considerTurnRestrictions',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set true to take turn restrictions into account',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPoints',
      type: 'boolean',
      defaultValue: 'false',
      description:
        'Set to true to remove detours due to via points (going back and forth on the same route)',
      documented: true,
    },
    {
      name: 'correctMisplacedViaPointsDistance',
      type: 'number',
      defaultValue: '400',
      description:
        'Only remove detours shorter than this (one-way) distance (in m) (engine defaults to 0 which removes detours whatever their length)',
      documented: true,
    },
    {
      name: 'downhillcost',
      type: 'number',
      defaultValue: '60',
      description: 'Cost for going downhill',
      documented: true,
    },
    {
      name: 'downhillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: 'Gradients below this value in percents are not counted.',
      documented: true,
    },
    {
      name: 'ignore_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set true for better elevation results',
      documented: true,
    },
    {
      name: 'maxSpeed',
      type: 'number',
      defaultValue: '45',
      description: 'Absolute maximum speed (in km/h), for travel time computation',
      documented: true,
    },
    {
      name: 'processUnusedTags',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set true to output unused tags in data tab',
      documented: true,
    },
    {
      name: 'S_C_x',
      type: 'number',
      defaultValue: '0.225',
      description:
        'Drag coefficient times the reference area (in m^2), for travel time computation',
      documented: true,
    },
    {
      name: 'stick_to_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set true to just follow cycleroutes',
      documented: true,
    },
    {
      name: 'totalMass',
      type: 'number',
      defaultValue: '90',
      description: 'Mass (in kg) of the bike + biker, for travel time computation',
      documented: true,
    },
    {
      name: 'turnInstructionCatchingRange',
      type: 'number',
      defaultValue: '40',
      description:
        'Within this distance (in m) several turning instructions are combined into one and the turning angles are better approximated to the general direction',
      documented: true,
    },
    {
      name: 'turnInstructionMode',
      type: 'number',
      defaultValue: '1',
      description:
        '%turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]',
      documented: false,
    },
    {
      name: 'turnInstructionRoundabouts',
      type: 'boolean',
      defaultValue: 'true',
      description: 'Set "false" to avoid generating special turning instructions for roundabouts',
      documented: true,
    },
    {
      name: 'uphillcost',
      type: 'number',
      defaultValue: '0',
      description: 'Cost for going uphill',
      documented: true,
    },
    {
      name: 'uphillcutoff',
      type: 'number',
      defaultValue: '1.5',
      description: 'Gradients below this value in percents are not counted.',
      documented: true,
    },
    {
      name: 'use_proposed_cycleroutes',
      type: 'boolean',
      defaultValue: 'false',
      description: 'Set to true to consider proposed and regular cycleroutes as equals',
      documented: true,
    },
    {
      name: 'validForBikes',
      type: 'boolean',
      defaultValue: 'true',
      description: '',
      documented: false,
    },
  ],
};

export const BROUTER_PROFILE_NAMES = [
  'fastbike',
  'fastbike-lowtraffic',
  'fastbike-verylowtraffic',
  'gravel',
  'hiking-beta',
  'hiking-mountain',
  'mtb',
  'MTB_SB_light',
  'racebike-verylowtraffic',
  'shortest',
  'trekking',
] as const;
export type BrouterProfileName = (typeof BROUTER_PROFILE_NAMES)[number];

/** Prüft, ob ein Profil einen Parameter überhaupt kennt. */
export function profileSupportsParameter(profile: string, parameter: string): boolean {
  const params = BROUTER_PROFILE_PARAMETERS[profile];
  if (!params) {
    return false;
  }
  return params.some((param) => param.name === parameter);
}
